version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
